import Link from 'next/link'
import { ArrowUpRight, Check, CircleGauge, Network, ShieldCheck, Sparkles } from 'lucide-react'
import { getResolvedContent } from '@/content/resolved'
import type { Locale } from '@/i18n/locales'
import { ServiceCard } from '@/components/ServiceCard'

const StreamLines=({bottom=false}:{bottom?:boolean})=><div className={`ref-streams ${bottom?'ref-streams-bottom':''}`} aria-hidden="true">{Array.from({length:17},(_,i)=><span key={i}/>)}</div>

export default async function Home({params}:{params:Promise<{locale:Locale}>}){
 const {locale}=await params; const t=getResolvedContent(locale)
 const services=[['01','energiebeschaffung',t.services.procurement],['02','strom',t.services.electricity],['03','gas',t.services.gas]] as const
 return <div className="ref-site">
  <section className="ref-hero"><StreamLines/><div className="ref-hero-glow"/><div className="shell ref-hero-copy"><p className="ref-kicker">Energiedienst Nord · Strom & Gas</p><h1>{t.home.title}</h1><p>{t.home.intro}</p><Link className="ref-button" href={`/${locale}/kontakt`}>{t.home.primary}<ArrowUpRight size={15}/></Link></div><div className="ref-scroll-line"><i/></div><div className="shell ref-app-shell" aria-hidden="true"><aside className="ref-app-nav"><div className="ref-app-brand"><span>EDN</span><small>ENERGY DESK</small></div><div className="ref-app-links"><b>Overview</b><span>Strom</span><span>Gas</span><span>Verträge</span></div></aside><div className="ref-app-main"><div className="ref-app-head"><div><small>ENERGIEÜBERSICHT</small><strong>Markt & Verträge</strong></div><span>LIVE</span></div><div className="ref-app-grid"><div className="ref-mini-card"><small>{t.services.electricity.title}</small><strong>12,8 ct</strong><i className="ref-bar ref-bar-green"/></div><div className="ref-mini-card"><small>{t.services.gas.title}</small><strong>4,9 ct</strong><i className="ref-bar ref-bar-purple"/></div><div className="ref-mini-card"><small>Monitoring</small><strong>24/7</strong><i className="ref-bar ref-bar-blue"/></div></div><div className="ref-chart-card"><div className="ref-chart-label"><span>MARKTENTWICKLUNG</span><small>12 MONATE</small></div><svg viewBox="0 0 700 160" preserveAspectRatio="none"><defs><linearGradient id="fadeA" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#8d80ff" stopOpacity=".24"/><stop offset="1" stopColor="#8d80ff" stopOpacity="0"/></linearGradient></defs><path className="ref-chart-area" d="M0 126 C55 112 80 134 125 106 S205 126 250 84 S335 112 390 70 S470 96 520 58 S610 82 700 42 L700 160 L0 160 Z"/><path className="ref-chart-line purple" d="M0 126 C55 112 80 134 125 106 S205 126 250 84 S335 112 390 70 S470 96 520 58 S610 82 700 42"/><path className="ref-chart-line green" d="M0 90 C60 68 105 102 160 74 S245 92 300 62 S375 78 430 52 S525 72 575 44 S645 59 700 30"/></svg></div></div></div></section>
  <section className="ref-intro"><div className="shell ref-centered-head"><p className="ref-kicker">{t.home.trustEyebrow}</p><h2>{t.home.trustTitle}</h2><p>{t.home.trustText1}</p></div><div className="shell ref-explainer"><div className="ref-accordion"><article className="active"><span>01</span><div><h3>{t.home.trustPrinciples[0]}</h3><p>{t.home.trustText2}</p></div></article><article><span>02</span><h3>{t.home.trustPrinciples[1]}</h3></article><article><span>03</span><h3>{t.home.trustPrinciples[2]}</h3></article></div><div className="ref-comparison-visual"><div className="ref-table"><div className="ref-table-head"><span>Anbieter</span><span>Tarif</span><span>Laufzeit</span></div>{['A','B','C','D','E'].map((r,i)=><div className="ref-table-row" key={r}><span>Energy {r}</span><i className={`ref-table-pill p${i%3}`}/><small>{12+i*3} M.</small></div>)}</div><div className="ref-floating-note"><span><Check size={14}/></span><strong>{t.home.providerTitle}</strong><small>{t.home.providerMetric}: 30+</small></div><div className="ref-column-chart">{[42,66,49,86,58,72].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div></div></div></section>
  <section id="services" className="ref-services"><div className="shell ref-centered-head ref-services-head"><p className="ref-kicker">{t.home.servicesEyebrow}</p><h2>{t.home.servicesTitle}</h2><p>{t.home.servicesText}</p></div><div className="shell ref-service-grid">{services.map(([i,slug,s])=><ServiceCard key={slug} index={i} slug={slug} service={s} locale={locale}/>)}</div></section>
  <section className="ref-network"><div className="shell ref-centered-head"><p className="ref-kicker">{t.home.providerEyebrow}</p><h2>{t.home.providerTitle}</h2><p>{t.home.providerText}</p></div><div className="shell ref-network-grid"><div className="ref-orb-card"><div className="ref-orb"><div className="ref-orb-inner"><strong>30+</strong><small>{t.home.providerMetric}</small></div></div><div className="ref-orb-caption"><Network size={15}/><span>Partnernetzwerk</span></div></div><div className="ref-difference-card"><div className="ref-difference-top"><Sparkles size={18}/><span>ENERGIEDIENST NORD</span></div><h3>{t.home.whyTitle}</h3><p>{t.home.whyText}</p><div className="ref-difference-points">{t.home.benefits.map((b:any,i:number)=><div key={b.title}><span>0{i+1}</span><strong>{b.title}</strong></div>)}</div></div></div></section>
  <section id="process" className="ref-process"><div className="shell ref-centered-head"><p className="ref-kicker">{t.home.processEyebrow}</p><h2>{t.home.processTitle}</h2></div><div className="shell ref-process-grid">{t.home.process.map((p:any,i:number)=><article key={p.n}><div className="ref-process-icon">{i===0?<CircleGauge size={18}/>:i===3?<ShieldCheck size={18}/>:<Sparkles size={18}/>}</div><span>{p.n}</span><h3>{p.title}</h3><p>{p.text}</p></article>)}</div></section>
  <section className="ref-cta-wrap"><div className="shell ref-cta"><div className="ref-cta-frame a"/><div className="ref-cta-frame b"/><div className="ref-cta-content"><span>EDN</span><h2>{t.home.ctaTitle}</h2><p>{t.home.ctaText}</p><Link className="ref-button" href={`/${locale}/kontakt`}>{t.home.primary}<ArrowUpRight size={15}/></Link></div><StreamLines bottom/></div></section>
 </div>
}
