import de from './de'
import en from './en'
import type { Locale } from '@/i18n/locales'

const overrides: Partial<Record<Locale, any>> = {
  fa: { nav:{services:'خدمات',company:'درباره ما',process:'روند همکاری',contact:'تماس',consultation:'درخواست مشاوره'}, home:{eyebrow:'Energiedienst Nord · مشاوره شفاف انرژی',title:'بازار پیچیده انرژی. تصمیم‌های روشن.',intro:'به مشتریان شخصی و تجاری برای انتخاب قراردادهای مناسب برق و گاز کمک می‌کنیم؛ شفاف، شخصی و قابل اعتماد.',primary:'درخواست مشاوره',secondary:'مشاهده خدمات',trustEyebrow:'اعتماد و مشاوره',trustTitle:'همراه قابل اعتماد شما برای برق و گاز.',trustText1:'ما به مشتریان شخصی و تجاری کمک می‌کنیم قراردادهای مناسب برق و گاز را پیدا کنند و با اطلاعات روشن تصمیم بگیرند.',trustText2:'هدف ما ساده‌کردن قیمت‌ها، پیشنهادها و مدل‌های قراردادی و یافتن راهکاری متناسب با نیاز واقعی شماست.',trustClaim:'مشاوره تخصصی. مقایسه شفاف. پشتیبانی قابل اعتماد.',trustPrinciples:['پشتیبانی شخصی','مشاوره شفاف','فرآیند قابل اعتماد'],providerEyebrow:'انتخاب و شبکه',providerTitle:'انتخاب گسترده. متناسب با شما.',providerMetric:'ارائه‌دهنده انرژی در شبکه ما',providerText:'از طریق شبکه بیش از ۳۰ تأمین‌کننده انرژی، به طیف گسترده‌ای از تعرفه‌های برق و گاز دسترسی داریم و گزینه‌های مناسب را بر اساس مصرف و نیاز شما مقایسه می‌کنیم.',servicesEyebrow:'خدمات ما',servicesTitle:'مشاوره انرژی برای تصمیم‌گیری ساده‌تر.',servicesText:'تمرکز ما روی برق و گاز است؛ از مقایسه تعرفه‌ها تا تهیه انرژی و پشتیبانی مستمر.',whyEyebrow:'چرا Energiedienst Nord',whyTitle:'مشاوره شخصی. مقایسه شفاف. همراهی قابل اعتماد.',whyText:'بازار انرژی پیچیده است. ما تفاوت‌ها را روشن می‌کنیم و تا رسیدن به راهکار مناسب کنار شما می‌مانیم.',ctaEyebrow:'مشاوره شخصی انرژی',ctaTitle:'با هم راهکار مناسب برق و گاز را پیدا کنیم.',ctaText:'در یک گفت‌وگوی اولیه بدون تعهد، شرایط شما را بررسی می‌کنیم.'}, company:{title:'مشاوره قابل اعتماد برای برق و گاز.',lead:'Energiedienst Nord یعنی مشاوره شخصی، مقایسه شفاف و همراهی مطمئن.'}, contact:{eyebrow:'تماس',title:'همه‌چیز با یک گفت‌وگوی خوب شروع می‌شود.',text:'شرایط فعلی برق یا گاز خود را کوتاه توضیح دهید؛ شخصاً با شما تماس می‌گیریم.'}, footer:{claim:'مشاوره شخصی و شفاف برای برق و گاز.'}},
  ar: { nav:{services:'الخدمات',company:'عن الشركة',process:'طريقة العمل',contact:'اتصل بنا',consultation:'اطلب استشارة'}, home:{eyebrow:'Energiedienst Nord · استشارات طاقة واضحة',title:'أسواق طاقة معقدة. قرارات واضحة.',intro:'نساعد العملاء الأفراد والشركات في اختيار عقود الكهرباء والغاز المناسبة بشفافية وخدمة شخصية وموثوقة.',primary:'احجز استشارة',secondary:'استكشف الخدمات',trustEyebrow:'الثقة والاستشارة',trustTitle:'شريكك الموثوق للكهرباء والغاز.',trustText1:'نساعد الأفراد والشركات على العثور على عقود كهرباء وغاز مناسبة واتخاذ قرارات مدروسة.',trustText2:'هدفنا تبسيط العروض والأسعار ونماذج العقود والوصول إلى حل يناسب احتياجاتك الفعلية.',trustClaim:'استشارة خبيرة. مقارنة شفافة. دعم موثوق.',trustPrinciples:['دعم شخصي','استشارة شفافة','إجراءات موثوقة'],providerEyebrow:'الاختيار والشبكة',providerTitle:'خيارات واسعة. مناسبة لاحتياجاتك.',providerMetric:'مزود طاقة ضمن شبكتنا',providerText:'من خلال شبكة تضم أكثر من 30 مزود طاقة، نقارن مجموعة واسعة من تعرفة الكهرباء والغاز وفق استهلاكك ومتطلباتك.',servicesEyebrow:'خدماتنا',servicesTitle:'استشارات طاقة تجعل القرار أسهل.',servicesText:'نركز على الكهرباء والغاز، من مقارنة التعرفة إلى التوريد والدعم المستمر.',whyEyebrow:'لماذا Energiedienst Nord',whyTitle:'استشارة شخصية. مقارنة شفافة. دعم موثوق.',whyText:'سوق الطاقة معقد، ونحن نوضح الفروق ونرافقك حتى الوصول إلى الحل المناسب.',ctaEyebrow:'استشارة طاقة شخصية',ctaTitle:'لنجد معًا الحل المناسب للكهرباء والغاز.',ctaText:'في محادثة أولية دون التزام نراجع وضعك ونوضح الخيارات المناسبة.'}, company:{title:'استشارات موثوقة للكهرباء والغاز.',lead:'تمثل Energiedienst Nord الاستشارة الشخصية والشفافية والدعم الموثوق.'}, contact:{eyebrow:'اتصل بنا',title:'الخطوة الأولى هي محادثة جيدة.',text:'أخبرنا باختصار عن وضع الكهرباء أو الغاز الحالي وسنتواصل معك شخصيًا.'}, footer:{claim:'استشارات شخصية وشفافة للكهرباء والغاز.'}},
  fr: {nav:{services:'Services',company:'Entreprise',process:'Notre méthode',contact:'Contact',consultation:'Demander un conseil'},home:{title:'Des marchés de l’énergie complexes. Des décisions claires.',intro:'Nous accompagnons particuliers et entreprises dans le choix de contrats d’électricité et de gaz adaptés, avec transparence et conseil personnalisé.',primary:'Prendre rendez-vous',secondary:'Découvrir nos services',trustEyebrow:'Confiance & conseil',trustTitle:'Votre partenaire fiable pour l’électricité et le gaz.',trustClaim:'Bien conseillé. Comparé en toute transparence. Accompagné avec fiabilité.',trustPrinciples:['Accompagnement personnel','Conseil transparent','Traitement fiable'],providerEyebrow:'Choix & réseau',providerTitle:'Un large choix. Adapté à vos besoins.',providerMetric:'fournisseurs d’énergie dans notre réseau',providerText:'Grâce à un réseau de plus de 30 fournisseurs, nous comparons une large sélection d’offres d’électricité et de gaz selon vos besoins.',servicesEyebrow:'Nos services',servicesTitle:'Un conseil énergétique qui simplifie vos décisions.',whyEyebrow:'Pourquoi Energiedienst Nord',whyTitle:'Conseil personnel. Comparaison transparente. Suivi fiable.'},contact:{eyebrow:'Contact',title:'Tout commence par un bon échange.'},footer:{claim:'Conseil personnel et transparent en électricité et gaz.'}},
  es: {nav:{services:'Servicios',company:'Empresa',process:'Cómo trabajamos',contact:'Contacto',consultation:'Solicitar asesoramiento'},home:{title:'Mercados energéticos complejos. Decisiones claras.',intro:'Ayudamos a particulares y empresas a elegir contratos adecuados de electricidad y gas con transparencia y asesoramiento personal.',primary:'Solicitar asesoramiento',secondary:'Ver servicios',trustEyebrow:'Confianza y asesoramiento',trustTitle:'Tu socio de confianza para electricidad y gas.',trustClaim:'Asesoramiento experto. Comparación transparente. Atención fiable.',trustPrinciples:['Atención personal','Asesoramiento transparente','Gestión fiable'],providerEyebrow:'Selección y red',providerTitle:'Amplia selección. Adaptada a ti.',providerMetric:'proveedores de energía en nuestra red',providerText:'Con una red de más de 30 proveedores, comparamos una amplia selección de tarifas de electricidad y gas según tus necesidades.',servicesEyebrow:'Nuestros servicios',servicesTitle:'Asesoramiento energético para decisiones más sencillas.',whyEyebrow:'Por qué Energiedienst Nord',whyTitle:'Asesoramiento personal. Comparación transparente. Apoyo fiable.'},contact:{eyebrow:'Contacto',title:'El primer paso es una buena conversación.'},footer:{claim:'Asesoramiento personal y transparente en electricidad y gas.'}},
  zh: {nav:{services:'服务',company:'关于我们',process:'服务流程',contact:'联系',consultation:'预约咨询'},home:{title:'复杂的能源市场。清晰的决策。',intro:'我们为个人和企业客户提供电力与天然气合同选择支持，透明、个性化且可靠。',primary:'预约咨询',secondary:'查看服务',trustEyebrow:'信任与咨询',trustTitle:'您可靠的电力与天然气合作伙伴。',trustClaim:'专业建议。透明比较。可靠服务。',trustPrinciples:['个性化服务','透明咨询','可靠办理'],providerEyebrow:'选择与网络',providerTitle:'更多选择，更贴合您的需求。',providerMetric:'家合作能源供应商',providerText:'依托30多家能源供应商网络，我们可比较多种电力和天然气方案，并根据您的用量和需求筛选合适选项。',servicesEyebrow:'我们的服务',servicesTitle:'让能源选择更简单。',whyEyebrow:'为什么选择我们',whyTitle:'个性化咨询。透明比较。可靠支持。'},contact:{eyebrow:'联系',title:'从一次良好的沟通开始。'},footer:{claim:'透明、个性化的电力与天然气咨询服务。'}},
  ja: {nav:{services:'サービス',company:'会社情報',process:'ご利用の流れ',contact:'お問い合わせ',consultation:'相談を予約'},home:{title:'複雑なエネルギー市場を、明確な判断へ。',intro:'個人・法人のお客様に、電気とガスの最適な契約選びを透明かつ丁寧にサポートします。',primary:'相談を予約',secondary:'サービスを見る',trustEyebrow:'信頼とアドバイス',trustTitle:'電気とガスの信頼できるパートナー。',trustClaim:'専門的な助言。透明な比較。信頼できるサポート。',trustPrinciples:['個別サポート','透明なアドバイス','確実な手続き'],providerEyebrow:'選択肢とネットワーク',providerTitle:'豊富な選択肢。あなたに合った提案。',providerMetric:'社以上のエネルギー事業者',providerText:'30社以上の事業者ネットワークを活用し、電気・ガス料金をニーズに合わせて比較します。',servicesEyebrow:'サービス',servicesTitle:'エネルギー選びをもっとシンプルに。',whyEyebrow:'選ばれる理由',whyTitle:'丁寧な相談。透明な比較。確かなサポート。'},contact:{eyebrow:'お問い合わせ',title:'まずはお気軽にご相談ください。'},footer:{claim:'電気とガスの透明で個別的なアドバイス。'}},
  ko: {nav:{services:'서비스',company:'회사 소개',process:'진행 방식',contact:'문의',consultation:'상담 요청'},home:{title:'복잡한 에너지 시장. 명확한 선택.',intro:'개인 및 기업 고객이 적합한 전기·가스 계약을 선택할 수 있도록 투명하고 개인화된 상담을 제공합니다.',primary:'상담 요청',secondary:'서비스 보기',trustEyebrow:'신뢰와 상담',trustTitle:'전기와 가스를 위한 믿을 수 있는 파트너.',trustClaim:'전문 상담. 투명한 비교. 신뢰할 수 있는 지원.',trustPrinciples:['개인 맞춤 지원','투명한 상담','신뢰할 수 있는 처리'],providerEyebrow:'선택과 네트워크',providerTitle:'폭넓은 선택. 나에게 맞는 제안.',providerMetric:'개 이상의 에너지 공급사',providerText:'30개 이상의 에너지 공급사 네트워크를 통해 다양한 전기 및 가스 요금제를 비교합니다.',servicesEyebrow:'서비스',servicesTitle:'에너지 선택을 더 쉽게.',whyEyebrow:'Energiedienst Nord를 선택하는 이유',whyTitle:'개인 상담. 투명한 비교. 신뢰할 수 있는 지원.'},contact:{eyebrow:'문의',title:'좋은 상담이 첫걸음입니다.'},footer:{claim:'전기와 가스를 위한 개인 맞춤형 투명 상담.'}},
  hi: {nav:{services:'सेवाएँ',company:'हमारे बारे में',process:'हम कैसे काम करते हैं',contact:'संपर्क',consultation:'परामर्श लें'},home:{title:'जटिल ऊर्जा बाज़ार। स्पष्ट निर्णय।',intro:'हम निजी और व्यावसायिक ग्राहकों को बिजली और गैस के उपयुक्त अनुबंध चुनने में पारदर्शी और व्यक्तिगत सहायता देते हैं।',primary:'परामर्श बुक करें',secondary:'सेवाएँ देखें',trustEyebrow:'विश्वास और परामर्श',trustTitle:'बिजली और गैस के लिए आपका विश्वसनीय भागीदार।',trustClaim:'विशेषज्ञ सलाह। पारदर्शी तुलना। विश्वसनीय सहायता।',trustPrinciples:['व्यक्तिगत सहायता','पारदर्शी सलाह','विश्वसनीय प्रक्रिया'],providerEyebrow:'विकल्प और नेटवर्क',providerTitle:'विस्तृत विकल्प। आपकी जरूरत के अनुसार।',providerMetric:'ऊर्जा प्रदाता हमारे नेटवर्क में',providerText:'30 से अधिक ऊर्जा प्रदाताओं के नेटवर्क से हम बिजली और गैस के कई विकल्पों की तुलना करते हैं।',servicesEyebrow:'हमारी सेवाएँ',servicesTitle:'ऊर्जा निर्णयों को आसान बनाना।',whyEyebrow:'हमें क्यों चुनें',whyTitle:'व्यक्तिगत सलाह। पारदर्शी तुलना। विश्वसनीय सहयोग।'},contact:{eyebrow:'संपर्क',title:'पहला कदम एक अच्छी बातचीत है।'},footer:{claim:'बिजली और गैस के लिए व्यक्तिगत और पारदर्शी सलाह।'}},
  tr: {nav:{services:'Hizmetler',company:'Hakkımızda',process:'Nasıl çalışıyoruz',contact:'İletişim',consultation:'Danışmanlık talebi'},home:{title:'Karmaşık enerji piyasaları. Net kararlar.',intro:'Bireysel ve ticari müşterilere uygun elektrik ve gaz sözleşmelerini bulmalarında şeffaf ve kişisel danışmanlık sunuyoruz.',primary:'Danışmanlık alın',secondary:'Hizmetleri keşfedin',trustEyebrow:'Güven & danışmanlık',trustTitle:'Elektrik ve gaz için güvenilir iş ortağınız.',trustClaim:'Uzman danışmanlık. Şeffaf karşılaştırma. Güvenilir destek.',trustPrinciples:['Kişisel destek','Şeffaf danışmanlık','Güvenilir süreç'],providerEyebrow:'Seçenek & ağ',providerTitle:'Geniş seçenek. Size özel çözüm.',providerMetric:'enerji sağlayıcısı ağımızda',providerText:'30’dan fazla enerji sağlayıcısından oluşan ağımız sayesinde elektrik ve gaz tarifelerini ihtiyaçlarınıza göre karşılaştırıyoruz.',servicesEyebrow:'Hizmetlerimiz',servicesTitle:'Enerji kararlarını kolaylaştıran danışmanlık.',whyEyebrow:'Neden Energiedienst Nord',whyTitle:'Kişisel danışmanlık. Şeffaf karşılaştırma. Güvenilir destek.'},contact:{eyebrow:'İletişim',title:'İlk adım iyi bir görüşmedir.'},footer:{claim:'Elektrik ve gaz için kişisel ve şeffaf danışmanlık.'}},
  pl: {nav:{services:'Usługi',company:'O nas',process:'Jak działamy',contact:'Kontakt',consultation:'Umów konsultację'},home:{title:'Złożony rynek energii. Jasne decyzje.',intro:'Pomagamy klientom prywatnym i firmom wybrać odpowiednie umowy na prąd i gaz w sposób przejrzysty i indywidualny.',primary:'Umów konsultację',secondary:'Zobacz usługi',trustEyebrow:'Zaufanie i doradztwo',trustTitle:'Twój niezawodny partner w zakresie prądu i gazu.',trustClaim:'Profesjonalne doradztwo. Przejrzyste porównanie. Niezawodne wsparcie.',trustPrinciples:['Indywidualna obsługa','Przejrzyste doradztwo','Sprawna realizacja'],providerEyebrow:'Wybór i sieć',providerTitle:'Duży wybór. Dopasowany do Ciebie.',providerMetric:'dostawców energii w naszej sieci',providerText:'Dzięki sieci ponad 30 dostawców porównujemy szeroki wybór taryf energii elektrycznej i gazu.',servicesEyebrow:'Nasze usługi',servicesTitle:'Doradztwo energetyczne, które ułatwia decyzje.',whyEyebrow:'Dlaczego Energiedienst Nord',whyTitle:'Indywidualnie. Przejrzyście. Niezawodnie.'},contact:{eyebrow:'Kontakt',title:'Pierwszym krokiem jest dobra rozmowa.'},footer:{claim:'Indywidualne i przejrzyste doradztwo w zakresie prądu i gazu.'}},
  ru: {nav:{services:'Услуги',company:'О компании',process:'Как мы работаем',contact:'Контакты',consultation:'Запросить консультацию'},home:{title:'Сложный рынок энергии. Понятные решения.',intro:'Мы помогаем частным и корпоративным клиентам выбирать подходящие договоры на электричество и газ прозрачно и индивидуально.',primary:'Записаться на консультацию',secondary:'Наши услуги',trustEyebrow:'Доверие и консультация',trustTitle:'Надёжный партнёр по электричеству и газу.',trustClaim:'Профессиональная консультация. Прозрачное сравнение. Надёжная поддержка.',trustPrinciples:['Персональная поддержка','Прозрачная консультация','Надёжное оформление'],providerEyebrow:'Выбор и сеть',providerTitle:'Большой выбор. Индивидуальный подход.',providerMetric:'поставщиков энергии в нашей сети',providerText:'Благодаря сети из более чем 30 поставщиков мы сравниваем широкий выбор тарифов на электричество и газ.',servicesEyebrow:'Наши услуги',servicesTitle:'Энергетическая консультация, упрощающая выбор.',whyEyebrow:'Почему Energiedienst Nord',whyTitle:'Персонально. Прозрачно. Надёжно.'},contact:{eyebrow:'Контакты',title:'Первый шаг — хороший разговор.'},footer:{claim:'Персональные и прозрачные консультации по электричеству и газу.'}},
  uk: {nav:{services:'Послуги',company:'Про нас',process:'Як ми працюємо',contact:'Контакти',consultation:'Замовити консультацію'},home:{title:'Складний енергоринок. Зрозумілі рішення.',intro:'Допомагаємо приватним і бізнес-клієнтам обирати відповідні договори на електроенергію та газ прозоро й персонально.',primary:'Замовити консультацію',secondary:'Переглянути послуги',trustEyebrow:'Довіра та консультація',trustTitle:'Ваш надійний партнер з електроенергії та газу.',trustClaim:'Професійна консультація. Прозоре порівняння. Надійна підтримка.',trustPrinciples:['Особистий супровід','Прозора консультація','Надійне оформлення'],providerEyebrow:'Вибір і мережа',providerTitle:'Широкий вибір. Підібрано для вас.',providerMetric:'постачальників енергії в нашій мережі',providerText:'Завдяки мережі з понад 30 постачальників ми порівнюємо широкий вибір тарифів на електроенергію та газ.',servicesEyebrow:'Наші послуги',servicesTitle:'Енергетичні консультації, що спрощують вибір.',whyEyebrow:'Чому Energiedienst Nord',whyTitle:'Особисто. Прозоро. Надійно.'},contact:{eyebrow:'Контакти',title:'Перший крок — хороша розмова.'},footer:{claim:'Персональні та прозорі консультації щодо електроенергії та газу.'}},
  it: {nav:{services:'Servizi',company:'Azienda',process:'Come lavoriamo',contact:'Contatti',consultation:'Richiedi consulenza'},home:{title:'Mercati energetici complessi. Decisioni chiare.',intro:'Aiutiamo privati e aziende a scegliere contratti di luce e gas adatti con consulenza trasparente e personale.',primary:'Richiedi consulenza',secondary:'Scopri i servizi',trustEyebrow:'Fiducia & consulenza',trustTitle:'Il tuo partner affidabile per luce e gas.',trustClaim:'Consulenza competente. Confronto trasparente. Assistenza affidabile.',trustPrinciples:['Assistenza personale','Consulenza trasparente','Gestione affidabile'],providerEyebrow:'Scelta & rete',providerTitle:'Ampia scelta. Su misura per te.',providerMetric:'fornitori di energia nella nostra rete',providerText:'Grazie a una rete di oltre 30 fornitori confrontiamo un’ampia selezione di tariffe luce e gas in base alle tue esigenze.',servicesEyebrow:'I nostri servizi',servicesTitle:'Consulenza energetica che semplifica le decisioni.',whyEyebrow:'Perché Energiedienst Nord',whyTitle:'Consulenza personale. Confronto trasparente. Supporto affidabile.'},contact:{eyebrow:'Contatti',title:'Il primo passo è una buona conversazione.'},footer:{claim:'Consulenza personale e trasparente per luce e gas.'}}
}

function deepMerge(base:any, patch:any):any {
  if (!patch) return base
  const out = {...base}
  for (const [key,value] of Object.entries(patch)) {
    if (value && typeof value === 'object' && !Array.isArray(value)) out[key] = deepMerge(base?.[key] ?? {}, value)
    else out[key] = value
  }
  return out
}

export function getContent(locale: Locale) {
  if (locale === 'de') return de
  if (locale === 'en') return en
  return deepMerge(en, overrides[locale])
}

export const dictionaries = Object.fromEntries((['de','en','fa','ar','fr','es','zh','ja','ko','hi','tr','pl','ru','uk','it'] as Locale[]).map(locale => [locale, getContent(locale)])) as Record<Locale, any>
